"""
إضافة جميع BINs البنوك القطرية من bintable.com
المصدر: https://bintable.com/country/qa (6 صفحات - 391 BIN)
"""

from pathlib import Path

QATAR_BINS_FULL = """
// ==================== البنوك القطرية الشاملة ====================
// المصدر: bintable.com/country/qa - 391 BIN
export const QATAR_BINS: Record<string, BinInfo> = {
  // ===== QNB - Qatar National Bank =====
  '559310': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  '558878': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'Corporate Executive' },
  '552467': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '552113': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '547432': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '545209': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '543820': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '542783': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '536547': { bank: 'QNB', network: 'Mastercard', type: 'Debit', tier: 'Business' },
  '533106': { bank: 'QNB', network: 'Mastercard', type: 'Debit', tier: 'World' },
  '532967': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'Corporate' },
  '532716': { bank: 'QNB', network: 'Mastercard', type: 'Debit', tier: 'Premium' },
  '532715': { bank: 'QNB', network: 'Mastercard', type: 'Debit', tier: 'World' },
  '531801': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '530776': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '530774': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '528617': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '527582': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '527384': { bank: 'QNB', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '526904': { bank: 'QNB', network: 'Mastercard', type: 'Debit', tier: 'Platinum' },
  '526850': { bank: 'QNB', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '526040': { bank: 'QNB', network: 'Mastercard', type: 'Debit', tier: 'Platinum' },
  '524270': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '524258': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '524192': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '524163': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '524150': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '523905': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '522449': { bank: 'QNB', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '521578': { bank: 'QNB', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '519957': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'World Elite' },
  '519288': { bank: 'QNB', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '517744': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '515902': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '514894': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '512843': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'World For Business' },
  '512664': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '511589': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '559307': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '524745': { bank: 'QNB', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  '524221': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '521020': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '535307': { bank: 'QNB', network: 'Mastercard', type: 'Debit', tier: 'World' },
  '526019': { bank: 'QNB', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  // QNB Visa
  '493818': { bank: 'QNB', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '493816': { bank: 'QNB', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '490981': { bank: 'QNB', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '469399': { bank: 'QNB', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '452339': { bank: 'QNB', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '452338': { bank: 'QNB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '442429': { bank: 'QNB', network: 'Visa', type: 'Credit', tier: 'Ultra High Net Worth' },
  '442422': { bank: 'QNB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '442421': { bank: 'QNB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '423305': { bank: 'QNB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '423304': { bank: 'QNB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '419252': { bank: 'QNB', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '419251': { bank: 'QNB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '419250': { bank: 'QNB', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '419249': { bank: 'QNB', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '476173': { bank: 'QNB', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '476174': { bank: 'QNB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '476175': { bank: 'QNB', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '476176': { bank: 'QNB', network: 'Visa', type: 'Debit', tier: 'Gold' },
  '494705': { bank: 'QNB', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '441330': { bank: 'QNB', network: 'Visa', type: 'Credit', tier: 'Standard' },

  // ===== Commercial Bank of Qatar (CBQ) =====
  '552400': { bank: 'Commercial Bank', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '547021': { bank: 'Commercial Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '543707': { bank: 'Commercial Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '541684': { bank: 'Commercial Bank', network: 'Mastercard', type: 'Credit', tier: 'World Black' },
  '540651': { bank: 'Commercial Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '538610': { bank: 'Commercial Bank', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '533123': { bank: 'Commercial Bank', network: 'Mastercard', type: 'Debit', tier: 'World' },
  '526900': { bank: 'Commercial Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '524497': { bank: 'Commercial Bank', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '522445': { bank: 'Commercial Bank', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '517741': { bank: 'Commercial Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '513322': { bank: 'Commercial Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '510471': { bank: 'Commercial Bank', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '639950': { bank: 'Commercial Bank', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  '639922': { bank: 'Commercial Bank', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  '639923': { bank: 'Commercial Bank', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  // CBQ Visa
  '498884': { bank: 'Commercial Bank', network: 'Visa', type: 'Credit', tier: 'Rewards' },
  '494047': { bank: 'Commercial Bank', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '491810': { bank: 'Commercial Bank', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '491809': { bank: 'Commercial Bank', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '474796': { bank: 'Commercial Bank', network: 'Visa', type: 'Debit', tier: 'Prepaid' },
  '471354': { bank: 'Commercial Bank', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '455000': { bank: 'Commercial Bank', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '434204': { bank: 'Commercial Bank', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '432438': { bank: 'Commercial Bank', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '431360': { bank: 'Commercial Bank', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '430198': { bank: 'Commercial Bank', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '424900': { bank: 'Commercial Bank', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '417485': { bank: 'Commercial Bank', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '416966': { bank: 'Commercial Bank', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '408389': { bank: 'Commercial Bank', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '408388': { bank: 'Commercial Bank', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '406626': { bank: 'Commercial Bank', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '400826': { bank: 'Commercial Bank', network: 'Visa', type: 'Credit', tier: 'Corporate T&E' },
  '400825': { bank: 'Commercial Bank', network: 'Visa', type: 'Credit', tier: 'Business Signature' },

  // ===== Qatar Islamic Bank (QIB) =====
  '557649': { bank: 'QIB', network: 'Mastercard', type: 'Debit', tier: 'Business' },
  '557628': { bank: 'QIB', network: 'Mastercard', type: 'Debit', tier: 'Platinum' },
  '543776': { bank: 'QIB', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '543735': { bank: 'QIB', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '543726': { bank: 'QIB', network: 'Mastercard', type: 'Debit', tier: 'Prepaid' },
  '533103': { bank: 'QIB', network: 'Mastercard', type: 'Debit', tier: 'World' },
  '512321': { bank: 'QIB', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  // QIB Visa
  '498622': { bank: 'QIB', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '489330': { bank: 'QIB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '489329': { bank: 'QIB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '489328': { bank: 'QIB', network: 'Visa', type: 'Debit', tier: 'Rewards' },
  '476854': { bank: 'QIB', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '476853': { bank: 'QIB', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '476852': { bank: 'QIB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '476851': { bank: 'QIB', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '464159': { bank: 'QIB', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '456526': { bank: 'QIB', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '456525': { bank: 'QIB', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '448382': { bank: 'QIB', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '433104': { bank: 'QIB', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '430747': { bank: 'QIB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '430742': { bank: 'QIB', network: 'Visa', type: 'Debit', tier: 'Prepaid' },
  '414393': { bank: 'QIB', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '414082': { bank: 'QIB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '412256': { bank: 'QIB', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '410805': { bank: 'QIB', network: 'Visa', type: 'Debit', tier: 'Infinite' },

  // ===== Masraf Al Rayan =====
  '497145': { bank: 'Masraf Al Rayan', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '489019': { bank: 'Masraf Al Rayan', network: 'Visa', type: 'Credit', tier: 'Corporate T&E' },
  '477779': { bank: 'Masraf Al Rayan', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '467895': { bank: 'Masraf Al Rayan', network: 'Visa', type: 'Debit', tier: 'Prepaid' },
  '457849': { bank: 'Masraf Al Rayan', network: 'Visa', type: 'Credit', tier: 'Ultra High Net Worth' },
  '456786': { bank: 'Masraf Al Rayan', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '425869': { bank: 'Masraf Al Rayan', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '423926': { bank: 'Masraf Al Rayan', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '417246': { bank: 'Masraf Al Rayan', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '416640': { bank: 'Masraf Al Rayan', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '416639': { bank: 'Masraf Al Rayan', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '416638': { bank: 'Masraf Al Rayan', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '405487': { bank: 'Masraf Al Rayan', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '402056': { bank: 'Masraf Al Rayan', network: 'Visa', type: 'Debit', tier: 'Prepaid' },
  '401633': { bank: 'Masraf Al Rayan', network: 'Visa', type: 'Debit', tier: 'Signature' },
  '428671': { bank: 'Masraf Al Rayan', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '428672': { bank: 'Masraf Al Rayan', network: 'Visa', type: 'Debit', tier: 'Gold' },
  '428673': { bank: 'Masraf Al Rayan', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '543357': { bank: 'Masraf Al Rayan', network: 'Mastercard', type: 'Debit', tier: 'Standard' },

  // ===== Doha Bank =====
  '541645': { bank: 'Doha Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '520419': { bank: 'Doha Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '520414': { bank: 'Doha Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '518917': { bank: 'Doha Bank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '512434': { bank: 'Doha Bank', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '510463': { bank: 'Doha Bank', network: 'Mastercard', type: 'Debit', tier: 'World' },
  // Doha Bank Visa
  '484823': { bank: 'Doha Bank', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '472839': { bank: 'Doha Bank', network: 'Visa', type: 'Debit', tier: 'Business' },
  '472481': { bank: 'Doha Bank', network: 'Visa', type: 'Credit', tier: 'Business' },
  '471369': { bank: 'Doha Bank', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '465202': { bank: 'Doha Bank', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '464423': { bank: 'Doha Bank', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '464422': { bank: 'Doha Bank', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '464421': { bank: 'Doha Bank', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '464400': { bank: 'Doha Bank', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '464470': { bank: 'Doha Bank', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '462035': { bank: 'Doha Bank', network: 'Visa', type: 'Credit', tier: 'Corporate T&E' },
  '446926': { bank: 'Doha Bank', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '434141': { bank: 'Doha Bank', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '434138': { bank: 'Doha Bank', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '428246': { bank: 'Doha Bank', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '428245': { bank: 'Doha Bank', network: 'Visa', type: 'Debit', tier: 'Prepaid' },
  '428133': { bank: 'Doha Bank', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '428132': { bank: 'Doha Bank', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '428131': { bank: 'Doha Bank', network: 'Visa', type: 'Debit', tier: 'Prepaid' },
  '419252': { bank: 'Doha Bank', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '419251': { bank: 'Doha Bank', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '419250': { bank: 'Doha Bank', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '419249': { bank: 'Doha Bank', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '464159': { bank: 'Doha Bank', network: 'Visa', type: 'Credit', tier: 'Signature' },

  // ===== QIIB - Qatar International Islamic Bank =====
  '471260': { bank: 'QIIB', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '471259': { bank: 'QIIB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '471258': { bank: 'QIIB', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '465002': { bank: 'QIIB', network: 'Visa', type: 'Debit', tier: 'Signature' },
  '458700': { bank: 'QIIB', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '443965': { bank: 'QIIB', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '426824': { bank: 'QIIB', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '426823': { bank: 'QIIB', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '426822': { bank: 'QIIB', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '417391': { bank: 'QIIB', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '411981': { bank: 'QIIB', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '410735': { bank: 'QIIB', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '410681': { bank: 'QIIB', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '410680': { bank: 'QIIB', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '440533': { bank: 'QIIB', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '445564': { bank: 'QIIB', network: 'Visa', type: 'Credit', tier: 'Infinite' },

  // ===== Ahlibank Qatar =====
  '543120': { bank: 'Ahlibank', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '523992': { bank: 'Ahlibank', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '449388': { bank: 'Ahlibank', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '449387': { bank: 'Ahlibank', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '443993': { bank: 'Ahlibank', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '443992': { bank: 'Ahlibank', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '433034': { bank: 'Ahlibank', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '433033': { bank: 'Ahlibank', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '429786': { bank: 'Ahlibank', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '483010': { bank: 'Ahlibank', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '483011': { bank: 'Ahlibank', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '483012': { bank: 'Ahlibank', network: 'Visa', type: 'Credit', tier: 'Infinite' },

  // ===== Barwa Bank (now Dukhan Bank) =====
  '527283': { bank: 'Dukhan Bank', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '527158': { bank: 'Dukhan Bank', network: 'Mastercard', type: 'Debit', tier: 'Platinum' },
  '516140': { bank: 'Dukhan Bank', network: 'Mastercard', type: 'Credit', tier: 'World' },
  '512713': { bank: 'Dukhan Bank', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '510463': { bank: 'Dukhan Bank', network: 'Mastercard', type: 'Debit', tier: 'World' },
  '458506': { bank: 'Dukhan Bank', network: 'Visa', type: 'Credit', tier: 'Corporate T&E' },
  '458454': { bank: 'Dukhan Bank', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '457659': { bank: 'Dukhan Bank', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '457658': { bank: 'Dukhan Bank', network: 'Visa', type: 'Debit', tier: 'Infinite' },
  '420375': { bank: 'Dukhan Bank', network: 'Visa', type: 'Debit', tier: 'Electron' },
  '420374': { bank: 'Dukhan Bank', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '420373': { bank: 'Dukhan Bank', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '420372': { bank: 'Dukhan Bank', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '432328': { bank: 'Dukhan Bank', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '434107': { bank: 'Dukhan Bank', network: 'Visa', type: 'Debit', tier: 'Prepaid' },

  // ===== Al Khaliji Commercial Bank =====
  '524503': { bank: 'Al Khaliji', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '473821': { bank: 'Al Khaliji', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '415180': { bank: 'Al Khaliji', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '415164': { bank: 'Al Khaliji', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '415163': { bank: 'Al Khaliji', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '415161': { bank: 'Al Khaliji', network: 'Visa', type: 'Credit', tier: 'Classic' },

  // ===== International Bank of Qatar (IBQ) =====
  '557686': { bank: 'IBQ', network: 'Mastercard', type: 'Debit', tier: 'Titanium' },
  '557685': { bank: 'IBQ', network: 'Mastercard', type: 'Debit', tier: 'Platinum' },
  '544126': { bank: 'IBQ', network: 'Mastercard', type: 'Credit', tier: 'Titanium' },
  '541509': { bank: 'IBQ', network: 'Mastercard', type: 'Credit', tier: 'Gold' },
  '536335': { bank: 'IBQ', network: 'Mastercard', type: 'Debit', tier: 'Standard' },
  '532704': { bank: 'IBQ', network: 'Mastercard', type: 'Debit', tier: 'World' },
  '475790': { bank: 'IBQ', network: 'Visa', type: 'Credit', tier: 'Signature' },
  '425886': { bank: 'IBQ', network: 'Visa', type: 'Credit', tier: 'Infinite' },
  '419587': { bank: 'IBQ', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '419586': { bank: 'IBQ', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '408597': { bank: 'IBQ', network: 'Visa', type: 'Credit', tier: 'Platinum' },

  // ===== HSBC Qatar =====
  '556613': { bank: 'HSBC Qatar', network: 'Mastercard', type: 'Credit', tier: 'Corporate' },
  '555355': { bank: 'HSBC Qatar', network: 'Mastercard', type: 'Credit', tier: 'Purchasing' },
  '552913': { bank: 'HSBC Qatar', network: 'Mastercard', type: 'Credit', tier: 'Purchasing' },
  '552067': { bank: 'HSBC Qatar', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '548128': { bank: 'HSBC Qatar', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '548127': { bank: 'HSBC Qatar', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '543198': { bank: 'HSBC Qatar', network: 'Mastercard', type: 'Credit', tier: 'Standard' },
  '543030': { bank: 'HSBC Qatar', network: 'Mastercard', type: 'Credit', tier: 'Corporate' },
  '526371': { bank: 'HSBC Qatar', network: 'Mastercard', type: 'Credit', tier: 'Corporate' },
  '517745': { bank: 'HSBC Qatar', network: 'Mastercard', type: 'Credit', tier: 'Platinum' },
  '455391': { bank: 'HSBC Qatar', network: 'Visa', type: 'Credit', tier: 'Standard' },
  '453928': { bank: 'HSBC Qatar', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '453927': { bank: 'HSBC Qatar', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '430599': { bank: 'HSBC Qatar', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '428686': { bank: 'HSBC Qatar', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '428685': { bank: 'HSBC Qatar', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '428684': { bank: 'HSBC Qatar', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '428683': { bank: 'HSBC Qatar', network: 'Visa', type: 'Debit', tier: 'Platinum' },
  '428682': { bank: 'HSBC Qatar', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '428681': { bank: 'HSBC Qatar', network: 'Visa', type: 'Debit', tier: 'Classic' },
  '418349': { bank: 'HSBC Qatar', network: 'Visa', type: 'Credit', tier: 'Platinum' },
  '418347': { bank: 'HSBC Qatar', network: 'Visa', type: 'Credit', tier: 'Gold' },
  '418346': { bank: 'HSBC Qatar', network: 'Visa', type: 'Credit', tier: 'Classic' },
  '432062': { bank: 'HSBC Qatar', network: 'Visa', type: 'Credit', tier: 'Standard' },
};
"""

# Read binDatabase.ts
ts_file = Path('/home/ubuntu/singlewindoo/client/src/lib/binDatabase.ts')
content = ts_file.read_text(encoding='utf-8')

# Replace existing QATAR_BINS
old_start = '// ==================== البنوك القطرية ===================='
old_end = '// قاعدة البيانات الموحدة'

start_idx = content.find(old_start)
end_idx = content.find(old_end)

if start_idx != -1 and end_idx != -1:
    new_content = content[:start_idx] + QATAR_BINS_FULL + '\n' + content[end_idx:]
    ts_file.write_text(new_content, encoding='utf-8')
    print("✅ Updated binDatabase.ts with full Qatar BINs")
else:
    print(f"❌ Pattern not found: start={start_idx}, end={end_idx}")
